#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 20 18:34:55 2018

@author: harshal
"""

# Create sound from frequency
import matplotlib.pyplot as plt
from scipy.fftpack import fft
from scipy.io import wavfile # get the api
import numpy as np

framerate = 44100


t_sample = 1.0 / framerate
time = 3
n_samples = time * framerate

x = np.linspace(0,n_samples -1, n_samples)
y = np.sin(2*np.pi*1200*x)*10000
data2 = np.c_[y,y]
wavfile.write('createsound_amp10000.wav',framerate,data2)